// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TgBotApi;

namespace TgBotApi.Migrations
{
    [DbContext(typeof(EngDbContext))]
    [Migration("20210601100648_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TgBotApi.Models.UserVocab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserVocabs");
                });

            modelBuilder.Entity("TgBotApi.Models.VocabItem", b =>
                {
                    b.Property<int>("VocabItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EnglishWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserVocabId")
                        .HasColumnType("int");

                    b.HasKey("VocabItemId");

                    b.HasIndex("UserVocabId");

                    b.ToTable("VocabItems");
                });

            modelBuilder.Entity("TgBotApi.Models.VocabItem", b =>
                {
                    b.HasOne("TgBotApi.Models.UserVocab", "UserVocab")
                        .WithMany("VocabItems")
                        .HasForeignKey("UserVocabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserVocab");
                });

            modelBuilder.Entity("TgBotApi.Models.UserVocab", b =>
                {
                    b.Navigation("VocabItems");
                });
#pragma warning restore 612, 618
        }
    }
}
